name: BambooCounter
main: fr.azrotho.bamboocounter.BambooCounter
version: 1.0
author: Azrotho
api-version: 1.20
commands:
  resettime:
    description: Reset the time of the counter
    usage: /resettime